<a href="https://colab.research.google.com/github/sasikalarajagopal25-pixel/python-numpy-Pandas/blob/main/Python_DA_Assignment_1_Data_Analysis_using_NumPy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Array Operations**

# **Create a 1D NumPy Array**

In [ ]:
import numpy as np
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1 )

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


# **Inspection and Properties**

Inspect the shape

In [ ]:
Shape = temperatures_w1.shape
print(Shape)

(7,)


Inspect the data type

In [ ]:
print("Data tpye:",temperatures_w1.dtype)

Data tpye: float64


In [ ]:
data_type = type(temperatures_w1)
print(data_type)

<class 'numpy.ndarray'>


In [ ]:
temperatures_w1.ndim

1

Number of elements in the array

In [ ]:
Number_of_element = temperatures_w1.size
print(Number_of_element)

7


# **Array Operations**

Convert the temperatures_w1 from Celsius to Fahrenheit using the
formula: Fahrenheit = (Celsius * 9/5) + 32

In [ ]:
Fahrenheit = (temperatures_w1 * 9/5) + 32
print ( f"Fahrenheit:",Fahrenheit)

Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]


Maximum Temperature

In [ ]:
print("Maximum:",temperatures_w1.max())

Maximum: 26.1


Minimum Temperature

In [ ]:
print("Minimum:",temperatures_w1.min())

Minimum: 20.8


Mean Temperature

In [ ]:
print("Mean:",round(temperatures_w1.mean()))

Mean: 24


In [ ]:
print("Mean:",(temperatures_w1.mean()))

Mean: 23.542857142857144


Extract the temperatures for the first three days of the week.

In [ ]:
print("First 3 days:",temperatures_w1[0:3])

First 3 days: [22.5 25.3 20.8]


Extract the temperatures for the weekend (last two days)

In [ ]:
print("Last 2 days:",temperatures_w1[5:])

Last 2 days: [24.8 21.9]


Extract the temperatures for the middle three days of the week

In [ ]:
print("Middle 3 days:",temperatures_w1[2:5])

Middle 3 days: [20.8 23.4 26.1]


# **Create a 2D Array**

In [ ]:
temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


Inspect and print the shape

In [ ]:
print("Shape:",temperatures.shape)

Shape: (2, 7)


Inspect and print the data tpye

In [ ]:
print("Data tpye:",temperatures.dtype)

Data tpye: float64


Inspect and print total number of elements in the
temperatures array.

In [ ]:
print("Number of element:",temperatures.size)

Number of element: 14


Extract the temperatures for each week and the weekends (last two days)
for both weeks.

In [ ]:
print("week1 last 2 days:",temperatures[0,5:])
print("week2 last 2 days:",temperatures[1,5:])

week1 last 2 days: [24.8 21.9]
week2 last 2 days: [22.8 20.1]


# **Pandas Series**

# **Creating Pandas Series**

In [ ]:
import pandas as pd

In [ ]:
Mark=[95, 92, 89, 85, 80]
Custom_Indices=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
marks = pd.Series(data=Mark,index=Custom_Indices)
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


# **Indexing and Slicing**

Use the integer index position to access the mark of the 1st rank student.

In [ ]:
first_rank_mark = marks.iloc[0]

print("Mark of 1st rank student:", first_rank_mark)

Mark of 1st rank student: 95


Use the loc accessor to retrieve the marks of the top 3 ranks by
specifying their index labels.

In [ ]:
top3_rank_mark = marks.loc['Rank1': 'Rank3']

print("Mark of 1st rank student:\n", top3_rank_mark)

Mark of 1st rank student:
 Rank1    95
Rank2    92
Rank3    89
dtype: int64


Use the iloc accessor to retrieve the mark of the 3rd rank student.

In [ ]:
third_rank_mark = marks.iloc[2]
print("3rd_rank_mark:",third_rank_mark)

3rd_rank_mark: 89


Apply a boolean mask to filter the Series and retrieve the ranks where the
marks are greater than 90.

In [ ]:
greater_than_90= marks[marks >90]
print("Greater than 90 marks:\n",greater_than_90)

Greater than 90 marks:
 Rank1    95
Rank2    92
dtype: int64


In [ ]:
print("boolean filter in greater than 90:\n",marks>90)

boolean filter in greater than 90:
 Rank1     True
Rank2     True
Rank3    False
Rank4    False
Rank5    False
dtype: bool


# **Manipulating Series**

Modify the mark of the student with the 1st rank to 100.

In [ ]:
marks[0]=100

/tmp/ipython-input-2657597664.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  marks[0]=100


In [ ]:
marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [ ]:
marks['Rank1']=100
marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

Remove the entry corresponding to the last rank from the Series.

In [ ]:
marks.drop('Rank5')

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

Compute the CGPA by dividing each mark in the Series by 10.

In [ ]:
marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [ ]:
CGPA = print("CGPA:\n", marks/10)
CGPA

CGPA:
 Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
Rank5     8.0
dtype: float64


# **Pandas DataFrame**

Creating Pandas DataFrame

In [ ]:
transactions={
    'TransactionID':[ 101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory':[ 'Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}
dataframe = pd.DataFrame(transactions,index=[1,2,3,4,5,6,7,8,9,10])
print(dataframe)

    TransactionID ProductCategory Region  Amount
1             101     Electronics  North     200
2             102        Clothing  South     150
3             103     Electronics  North     300
4             104       Furniture   East     450
5             105        Clothing   West     200
6             106     Electronics  North     250
7             107       Furniture   East     300
8             108        Clothing   West     180
9             109       Furniture  South     350
10            110     Electronics  North     400


# **Data Exploration**

Display the transactions DataFrame and its basic information, including
head, tail, shape, column names, and data types.

In [ ]:
dataframe.head(3)

TransactionID ProductCategory Region  Amount
1            101     Electronics  North     200
2            102        Clothing  South     150
3            103     Electronics  North     300

In [ ]:
dataframe.tail(2)

TransactionID ProductCategory Region  Amount
9             109       Furniture  South     350
10            110     Electronics  North     400

In [ ]:
dataframe.shape

(10, 4)

In [ ]:
dataframe.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

In [ ]:
dataframe.dtypes

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

Display only the 'ProductCategory' and 'Amount' columns.

In [ ]:
dataframe[['ProductCategory','Amount']]

ProductCategory  Amount
1      Electronics     200
2         Clothing     150
3      Electronics     300
4        Furniture     450
5         Clothing     200
6      Electronics     250
7        Furniture     300
8         Clothing     180
9        Furniture     350
10     Electronics     400

Retrieve the last 3 columns of the DataFrame using iloc or loc.

In [ ]:
dataframe.iloc[7:]

TransactionID ProductCategory Region  Amount
8             108        Clothing   West     180
9             109       Furniture  South     350
10            110     Electronics  North     400

Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

In [ ]:
filtered_df = dataframe[(dataframe['Region'] == 'North') & (dataframe['Amount'] > 200)]
(filtered_df)

TransactionID ProductCategory Region  Amount
3             103     Electronics  North     300
6             106     Electronics  North     250
10            110     Electronics  North     400

Find the value counts for the 'ProductCategory' column.


In [ ]:
count_product_category = dataframe['ProductCategory'].count()
print("count_product_category:",count_product_category)

count_product_category: 10


Find the unique values in the 'Region' column.

In [ ]:
Unique_value_region= dataframe['Region'].unique()
print("Unique_value:",Unique_value_region)

Unique_value: ['North' 'South' 'East' 'West']


Group by 'Region' and find the mean amount for each region.

In [ ]:
group_region=dataframe.groupby('Region')['Amount'].mean()
group_region

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

# **Manipulating the DataFrame**

Modify the 'Amount' for the transaction with TransactionID 102 to 165

In [ ]:
modify_amount=dataframe.loc[dataframe['TransactionID']==102,'Amount']=165
dataframe

TransactionID ProductCategory Region  Amount
1             101     Electronics  North     200
2             102        Clothing  South     165
3             103     Electronics  North     300
4             104       Furniture   East     450
5             105        Clothing   West     200
6             106     Electronics  North     250
7             107       Furniture   East     300
8             108        Clothing   West     180
9             109       Furniture  South     350
10            110     Electronics  North     400

Add a new column 'Discount' by calculating 10% of the 'Amount'

In [ ]:
dataframe['Discount']=dataframe['Amount'].apply(lambda x:x*0.1)
dataframe

TransactionID ProductCategory Region  Amount  Discount
1             101     Electronics  North     200      20.0
2             102        Clothing  South     165      16.5
3             103     Electronics  North     300      30.0
4             104       Furniture   East     450      45.0
5             105        Clothing   West     200      20.0
6             106     Electronics  North     250      25.0
7             107       Furniture   East     300      30.0
8             108        Clothing   West     180      18.0
9             109       Furniture  South     350      35.0
10            110     Electronics  North     400      40.0

Remove the row with TransactionID 109

In [ ]:
dataframe.drop(9)

TransactionID ProductCategory Region  Amount  Discount
1             101     Electronics  North     200      20.0
2             102        Clothing  South     165      16.5
3             103     Electronics  North     300      30.0
4             104       Furniture   East     450      45.0
5             105        Clothing   West     200      20.0
6             106     Electronics  North     250      25.0
7             107       Furniture   East     300      30.0
8             108        Clothing   West     180      18.0
10            110     Electronics  North     400      40.0

Delete the 'Discount' column from the DataFrame

In [ ]:
dataframe.drop('Discount',axis=1)

TransactionID ProductCategory Region  Amount
1             101     Electronics  North     200
2             102        Clothing  South     165
3             103     Electronics  North     300
4             104       Furniture   East     450
5             105        Clothing   West     200
6             106     Electronics  North     250
7             107       Furniture   East     300
8             108        Clothing   West     180
9             109       Furniture  South     350
10            110     Electronics  North     400